fix sig.replace to account for kwargs (#750)
If the `selected_wrapper` function contains a `**kwargs` parameters,
`sig.replace(...)` breaks because of the following error:
```
ValueError: wrong parameter order: variadic keyword parameter before keyword-only parameter
```

This PR fixes the above error.

Co-authored-by: McCheng <marcocheng@setsailsoftware.com>